# Generated by Django 3.2 on 2023-04-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='encryptedpassword',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='password',
            field=models.CharField(default='3201', max_length=40, null=True),
        ),
    ]
