# Generated by Django 3.2 on 2023-05-02 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20230428_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='IDNumber',
            field=models.CharField(default='', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Required 9 Digit ID Number', regex='^[0-9]{4}$')]),
        ),
    ]
