# Generated by Django 3.2 on 2023-05-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_faculty_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Attendance',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
